# Shared osxcross settings for Darwin.

set (CMAKE_SYSTEM_NAME Darwin)
set (CMAKE_OSX_DEPLOYMENT_TARGET "11.0" CACHE STRING "")

if (DEFINED ENV{SDKROOT} AND EXISTS "$ENV{SDKROOT}")
  set (CMAKE_OSX_SYSROOT "$ENV{SDKROOT}" CACHE PATH "")
elseif (DEFINED ENV{OSXCROSS_SDK} AND EXISTS "$ENV{OSXCROSS_SDK}")
  set (CMAKE_OSX_SYSROOT "$ENV{OSXCROSS_SDK}" CACHE PATH "")
endif ()

include (${CMAKE_CURRENT_LIST_DIR}/osxcross-tools.cmake)
