name: CD

on:
  release:
    types: [created]

concurrency:
  group: cd-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/ci.yml
    permissions:
      contents: write
    with:
      publish_release: true
    secrets: inherit
